name: Azure Static Web Apps CI/CD

on: 
  push: 
    branches: 
      - master 
  pull_request: 
    types: [opened, synchronize, reopened, closed] 
    branches: 
      - master 

permissions:
  contents: read

jobs: 
  build_and_deploy_job: 
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed') 
    runs-on: ubuntu-latest 
    name: Build and Deploy Job 
    steps: 
      - uses: actions/checkout@v3 
        with: 
          submodules: true 
          lfs: false 
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build Angular app
        run: npm run build:prod
        env:
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
          FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
      
      - name: Build And Deploy 
        id: builddeploy 
        uses: Azure/static-web-apps-deploy@v1
        with: 
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_SALMON_BUSH_0E3C36110 }} 
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments) 
          action: "upload" 
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ###### 
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig 
          app_location: "dist/notus-angular" # Built app content directory
          api_location: "" # Api source code path - optional
          output_location: "" # Built app content directory - not needed when app_location points to built files
          ###### End of Repository/Build Configurations ###### 

  close_pull_request_job: 
    if: github.event_name == 'pull_request' && github.event.action == 'closed' 
    runs-on: ubuntu-latest 
    name: Close Pull Request Job 
    steps: 
      - name: Close Pull Request 
        id: closepullrequest 
        uses: Azure/static-web-apps-deploy@v1
        with: 
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_SALMON_BUSH_0E3C36110 }} 
          action: "close"
