name: Autocloser
on: [issues]

permissions:
  issues: write

jobs:
  autoclose:
    runs-on: ubuntu-latest
    steps:
    - name: Issue auto-closer
      uses: roots/issue-closer-action@v1.1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-close-message: "@${{ github.event.issue.user.login }} esta issue foi fechada automaticamente porque não seguiu nossas regras:\n\n<pre>\n\nPor favor, siga as diretrizes ao criar uma nova issue.\n\nObrigado!"
        issue-pattern: (\#\#\# Versão([\S\s.*]*?)\#\#\# Link de Reprodução([\S\s.*]*?)\#\#\# Sistema Operacional([\S\s.*]*?)\#\#\# Dispositivo([\S\s.*]*?)\#\#\# Navegador e Versão([\S\s.*]*?)\#\#\# Passos para reproduzir([\S\s.*]*?)\#\#\# O que é esperado([\S\s.*]*?)\#\#\# O que está realmente acontecendo([\S\s.*]*?)---([\S\s.*]*?)\#\#\# Solução([\S\s.*]*?)\#\#\# Comentários adicionais([\S\s.*]*?)\<\!-- gerado por \. NÃO REMOVA --\>)|(\#\#\# Qual é a sua melhoria([\S\s.*]*?)\)